### ISSUE TITLE
Implement importValue logic

### ISSUE THREAD

**Issue by filippomc** [openworm/org.geppetto.python#23]
In order to implement the importValue logic we need the following in place:
1. `GeppettoManager.resolveImportValue`: this is starting the whole thing
1. `DataManager.getGeppettoProjectById`: needed to load the current runtimeProject. We could start with a default naive data manager always returning the same project and leave the pluggable data managers to a second phase.
1. `RuntimeProject.resolveImportValue`: here we have the main general model related logic
    - `PointerUtility.getValue`: here we have the logic which traverses the model and finds the value at the given path
    - `GeppettoModelAccess.getType`: the GeppettoModelAccess helps us inspecting the model
1. `ModelInterpreter` interface and discovery. We also need a way to find model interpreters. Here we don't have the osgi resolving the pluggable services, so we must change this logic. We may set a function allowing to register model interpreters from outside. See also `CreateModelInterpreterServicesVisitor.caseImportType` for the logic which associates the modelInterpreter to a library in Java.

High level flow coming from Java:
![Geppetto backend high level design - ImportValue flow](https://user-images.githubusercontent.com/46561561/55339119-580a0e80-54a2-11e9-94e4-1b4a0b8321d3.png)

**Comment by filippomc** [comment]
@tarelli please revise if I'm missing something important

**Comment by aranega** [comment]
@filippometacell For this, indeed, the work I started to perform on the `feature/managers` branch can be a good entry point. I put some logic in the `GeppettoManager` and tests. Everything is not here (obviously), but things should be split in a more or less nice way.

**Comment by filippomc** [comment]
Thanks I'm starting coding from feature/managers, there's the whole structure I can reuse and I can see many parts of logic already implemented, it's going smoothly for now!
