### ISSUE TITLE
Can't clone ecore objects

### ISSUE THREAD

**Issue by filippomc** [openworm/org.geppetto.python#26]
The cloning is needed when parts of the model are reused, as is the case of the geppetto main library.
In Java there is the ecore utils which provides the cloning, which is missing on pyecore.
Tried different out of the box strategies which are not working:
- Python copy.deepcopy
- Pickle
- Dill

Specifically for the library we can reload the resource from the xmi file for each new project, but then there is some messing up of references when serializing.

Possible solutions:
 - Implement a cloning utility like Java ecore
 - Use the json serialization/deserialization

**Comment by filippomc** [comment]
@aranega what do you think?

**Comment by aranega** [comment]
Hi @filippometacell
 
Sorry for the delay. Indeed, PyEcore doesn't yet cloning capabilities for `EObject`, and it should be. It's something that would be useful anyone. I worked quickly on a first version today, but I will not add it directly to PyEcore as further testing is still required. I give you the code here as you could test it and tell me if the behavior matches the one you would like (there is several cases):

```python
def clone(eobject, skip_containment=False, skip_refs=False):
    if not isinstance(eobject, EObject) and not isinstance(eobject, type):
        return eobject
    if isinstance(eobject, type):
        eobject = eobject.eClass

    def create_instance(original):
        if isinstance(original, type):
            original = original.eClass
            cloned_object = original.eClass(original.name)
        elif original.eClass is EClass.eClass:
            cloned_object = original.eClass(original.name)
        else:
            cloned_object = original.eClass()
        return cloned_object

    def first_setup(original, cloned):
        references = []
        for feature in original._isset:
            if isinstance(feature, EReference):
                if skip_refs:
                    continue
                opposite = feature.eOpposite
                if opposite and (opposite.containment or opposite in references):
                    continue
                if skip_containment and feature.containment:
                    continue
                references.append(feature)
                continue
            if feature.many:
                cloned.eGet(feature).extend(original.eGet(feature))
            else:
                cloned.eSet(feature, original.eGet(feature))
        return references

    created_elements = {}
    clone_refs = {}
    all_objects = [eobject]
    if not skip_containment:
        all_objects.extend(eobject.eAllContents())

    for e in all_objects:
        cloned = create_instance(e)
        created_elements[e] = cloned
        clone_refs[e] = (cloned, first_setup(e, cloned))

    if skip_refs:
        return created_elements.get(eobject)

    for original, (cloned, refs) in clone_refs.items():
        for feature in refs:
            if feature.many:
                eobjs = [created_elements.get(x, x) for x in original.eGet(feature)]
                cloned.eGet(feature).extend(eobjs)
            else:
                obj = original.eGet(feature)
                cloned.eSet(feature, created_elements.get(obj, obj))
    return created_elements.get(eobject)
```

Also this is a first version and if clearly requires some refactoring. The default behavior is the following: applied to an object, it copies it and copies all its children. It also affects the attributes to the rights values and deal with references on its own (meaning that if two elements in the children references each others, they will reference their copies in the clone children):

```
>>> clone(A)

   A              A
  / \     copy   / \
 B - C          B - C
```

if a clone is asked on a sub element directly (ex: `C`), the clone function does not copy it's sibiling or elements it is linked through non containment relationships:

```
>>> clone(C)

   A              
  / \     copy  
 B - C            C   (in this case, C copy points to B)
  \--------------/
```

You have two options that could impact the cloning, `skip_containment` which skips the element feature that are containments and `skip_refs` that prevent from assigning references to the cloned object (meaning that only the attributes are copied to the cloned instance).

In your case, it means that if you have the root of a model you want to clone, you would have to just call `clone(my_root)` to have a copy of your root and all it's children. This algorithm could change and I didn't checked the original EMF behavior, so it could evolve to match or not it's behavior (or to add/remove functionnalities from it).

Tell me if that could be a fit to what you want. Starting tomorrow, I take some weeks off, meaning that I will have a lot of time in the plane to code. If there is things you don't like or you would change, please tell me, I will gladely change them if you need.

**Comment by filippomc** [comment]
Thanks @aranega, I'll be testing that and give some feedback right away.

**Comment by filippomc** [comment]
The cloning seems correct from my tests by itself. Still there is a subtle problem that messes up references within the copy when mixing originals and clones.

Let's say I have a library `L` with type `T` contained and `L'` which is its copy
If we create a model with library `L` a variable `V `of type `T' `of `L'` the reference is not correct when serializing the object because it's beloging  from a different resources.

When serialized, the reference into the variable looks like this:
`"$ref": "<pyecore.resources.resource.URI object at 0x7ff611efb470>//@types.2"\n`
instead of 
`"$ref": "//@libraries.0/@types.2"\n          },\n `

So we have 2 possible causes of error coming from json.py  object_uri method)
1. https://github.com/pyecore/pyecore/blob/22b67ad8799594f8f44fd8bee497583d4f12ed63/pyecore/resources/json.py#L79 the equality control looks for identity so it not fit to work with clones
1. https://github.com/pyecore/pyecore/blob/22b67ad8799594f8f44fd8bee497583d4f12ed63/pyecore/resources/json.py#L83 The print of the resource is not correct


Here is my test code:
```Python
def test_clone_geppetto_library():
    model_factory = GeppettoModelFactory()
    model = GeppettoModel(name='modelname', libraries=[clone(model_factory.geppetto_common_library)])
    model.variables.append(model_factory.createStateVariable('varname'))

    print(GeppettoSerializer.serialize(model))

    model2 = GeppettoModel(name='modelname', libraries=[model_factory.geppetto_common_library])
    model2.variables.append(model_factory.createStateVariable('varname'))
    print(GeppettoSerializer.serialize(model))

    assert json.loads(GeppettoSerializer.serialize(model)) == json.loads(GeppettoSerializer.serialize(model2))
```

**Comment by aranega** [comment]
@filippometacell Thanks for the test and thanks for the test case. I will work on that quickly! 

The way the distant URI is serialized is not good in any cases, which means that you probably found a bug. I wonder if I indtroduced that in the last version of PyEcore because cross-references where working well before... Thanks so much for spotting it!

**Comment by aranega** [comment]
@filippometacell Ok, there is definitely something bad in the way the URI for other resources are created, I will fix that. Thanks again for having spoted the bug :) !

However, there's something that it's weird to me in the way the `createStateVariable(...)` method works. It definitly reference the object in another model, so that's why at serialization time it tries to add the URI of the other resource. Did you modified something in the way the default EMF copier works? Otherwise, I don't understand how EMF is able to understand that two different object actually represent the same one and thus does not add the cross-reference URI resource marker during serialization.

**Comment by filippomc** [comment]
@aranega I've looked at the Java version and there is in fact a logic we're being missing in pygeppetto that is taking the reference of the library from the same model, using a global reference instead. In Java we create a state variable like this
`commonLibraryAccess.getType(TypesPackage.Literals.STATE_VARIABLE_TYPE)`, were `commonLibraryAccess ` is an objects of type `GeppettoModelAccess` that knows in fact the current model and takes the same library from there. I'm going to change that logic.
Thanks for your help
