### ISSUE TITLE
Econtainers are not consistenty set

### ISSUE THREAD

**Issue by filippomc** [openworm/org.geppetto.python#30]
It seems that the eContainer is not initialized in meta type objects.
Example:
```
variable = Variable(id=id)
variable.types.append(self.geppetto_common_library.types[2])
variable.eContainer() # None
```

**Comment by tarelli** [comment]
There you are saying that the type of a variable is a type coming from the common library but the variable itself is not contained anywhere so None is correct.

As an example if you add that variable to a GeppettoModel or to a CompositeType and then check the container it will be populated.

**Comment by filippomc** [comment]
Ok I was supposing that the container was the type in that case but that's clearly wrong. Thanks.
