### ISSUE TITLE
Duplicated values in lists are merged

### ISSUE THREAD

**Issue by filippomc** [openworm/org.geppetto.python#50]
The following test should not fail:

```Python
from pygeppetto.model import  QueryResults
query_result = QueryResult(values=["a", "a"])
assert len(query_result.values) == 2
```
This is related to the fact that QueryResult.values is of type `OrderedSet`.
This is related to something we already seen for time series.

@aranega is there a way to solve this without patching the generated code?

**Comment by aranega** [comment]
@filippomc I'll check tomorrow. The problem sounds to come from a bad generation as the `.ecore` file sounds like a good. The last time I tried to reproduce the bug in the code generation, I was not able to. I'll try with a different context because perhaps I have something that prevent it to rise.

**Comment by aranega** [comment]
@filippomc I reproduced the bug, I was testing the wrong kind of associations... (`EReference` instead of `EAttribute`), the issue is in pyecoregen. I'll propose a patch for it. At the same time, I'll generate in local the new metamodel and use meld to change the properties where it's necessary, and I'll propose it as a PR for you to integrate.

**Comment by filippomc** [comment]
Hi @aranega thanks a lot for your help. I can easily patch objects in pygeppetto following what you suggested for the Time Series a while ago and I have already a workaround for my business case, so no need to use your time on that. Please let me know when the patch is available I'll be happy to do some testing.

**Comment by aranega** [comment]
@filippomc I proposed the patch for pyecoregen to include `unique=False` when it's required. However, I'm not maintaining pyecoregen, so we have to wait for the PR approval ;) . Also, this patch will only ad the missing property, but it will not do the trickery to improve performances by removing runtime type checking, you'll have to add this one back by hand.

**Comment by filippomc** [comment]
Thanks a lot @aranega, let's wait for the approval :) The performance issue is surely minor respect to this, which can possibly cause subtle bugs in the application
