### ISSUE TITLE
Change root package name?

### ISSUE THREAD

**Issue by aranega** [openworm/org.geppetto.python#8]
I was trying to play a little bit with pygeppetto to test some new additions in pyecore on [this online repl](https://repl.it/languages/python2) (which can automatically install pypi packages), but unfortunately, `pygeppetto` coun't be installed. This repl installs packages by matching the import name with the package name on pypi, and, the root package `model` does not match the `pygeppetto` name on pypi. 

The `pygeppetto` API is built from the `.ecore`, and generated package is named after the name of the root `EPackage` in the model (named `model`), which is fine in a way, it respects what have been introduced in the metamodel, but I'm sure the result matches Python's best practices for packages building. I could change that, there is two ways: 

1. directly rename the `model` package to `pygeppetto`,
1. introduce a new package `pygeppetto` which will contain the `model` package.

The great part is that you will have a more "clean" first package/API, but the downside is that imports in existing code that uses `pygeppetto` should be modified (with the two solutions). So, here's the potential scenarios:

**Scenario 1>** There is no need to change the package name, everybody is happy with it, so, the ticket is closed :)

**Scenario 2>** I PR a change for the package name from `model` to `pygeppetto`. With this modifications, import should change like this:

```python
# before
import model   # or
import model as pygeppetto  # or
from model import Composite
# ... following the used import, usage could change also

# after
import pygeppetto
from pygeppetto import Composite  # or
```

**Scenario 3>** I PR a change that introduce a new package level named `pygeppetto`. With this modifications, import should change like this:

```python
# before
import model   # or
import model as pygeppetto  # or
from model import Composite
# ... following the used import, usage could change also

# after
import pygeppetto.model
from pygeppetto import model  # or
from pygeppetto.model import Composite  # or
```

Finally, the question, is: Is this project name <-> root package name mismatching is problematic for you guys or you can live with it?

**Comment by tarelli** [comment]
@aranega thanks for looking into this Vincent! I had in my list of tasks to ask you about this. Essentially we started using pygeppetto for more than the model so what I was going to ask is if it's possible to refactor it such that model is contained inside pygeppetto (scenario 3). I don't mind change where we are importing it because ultimately it will be a better structure. Does it seem sensible? Thanks again!

**Comment by aranega** [comment]
@tarelli Got it! No problem, I should have proposed this in the first place and not so lately. I will do the PR asap. I can help you change the imports on other projects if you need.
I will also provide another PR that would let `pygeppetto` be compatible with Python 2 and 3 at the same time (I think I have all I need in pyecore), if that's ok with you.

**Comment by tarelli** [comment]
@aranega that would be fantastic cause we started having competing forces with some projects needing 2 and some other needing 3!

**Comment by aranega** [comment]
@tarelli I will try to do this as quickly as I can!

**Comment by gidili** [comment]
@aranega this (python 3 compatibility) is nothing short of telepathy we were talking about this just last night! 😂
